-- clear tables

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE students';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE groups';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- TASK 1
CREATE TABLE students(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    group_id NUMBER
);

CREATE TABLE groups(
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    students_count NUMBER NOT NULL
);

INSERT INTO students(name, group_id) VALUES('Alex', 1);
INSERT INTO students(name, group_id) VALUES('Ivan', 1);
INSERT INTO students(name, group_id) VALUES('Katya', 2);
INSERT INTO students(name, group_id) VALUES('Masha', 1);
INSERT INTO students(name, group_id) VALUES('Roma', 2);
INSERT INTO students(name, group_id) VALUES('Kostya', 2);
INSERT INTO students(name, group_id) VALUES('Yars', 3);
INSERT INTO students(name, group_id) VALUES('Angelina', 3);
INSERT INTO students(name, group_id) VALUES('Polina', 3);


INSERT INTO groups(id, name, students_count) VALUES(1, 'Group A', 0);
INSERT INTO groups(id, name, students_count) VALUES(2, 'Group B', 0);
INSERT INTO groups(id, name, students_count) VALUES(3, 'Group C', 0);