DROP VIEW IF EXISTS persons_room CASCADE;

DROP TABLE IF EXISTS used_entertainments CASCADE;
DROP TABLE IF EXISTS used_procedures CASCADE;
DROP TABLE IF EXISTS serviced_procedures CASCADE;
DROP TABLE IF EXISTS visited_events CASCADE;
DROP TABLE IF EXISTS extra_events CASCADE;
DROP TABLE IF EXISTS procedures CASCADE;
DROP TABLE IF EXISTS entertainments CASCADE;
DROP TABLE IF EXISTS vacationers CASCADE;
DROP TABLE IF EXISTS administrators CASCADE ;
DROP TABLE IF EXISTS medical_employees CASCADE;
DROP TABLE IF EXISTS logging CASCADE;
DROP TABLE IF EXISTS medical_jobs CASCADE;
DROP TABLE IF EXISTS abstract_users CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;