ALTER SESSION SET "_ORACLE_SCRIPT"=true; 

DROP USER DEV_SCHEMA CASCADE;
DROP USER PROD_SCHEMA CASCADE;

CREATE USER DEV_SCHEMA IDENTIFIED BY DEV_PASSWORD;
GRANT ALL PRIVILEGES TO DEV_SCHEMA;

CREATE USER PROD_SCHEMA IDENTIFIED BY PROD_PASSWORD;
GRANT ALL PRIVILEGES TO PROD_SCHEMA;